# -*- coding: utf-8 -*-
# Çıkmış final sınavları (taranmış PDF'lerden transkribe edildi).
# correct = doğru şıkkın index'i (0=A). exp = Türkçe açıklama.

EXAMS = []

# ===========================================================================
# 2024–2025 FINAL (CEN302) — 21 Mayıs 2025 — 50 soru (net taranmış)
# ===========================================================================
EXAMS.append({
"id": "sinav2425",
"year": "2024–2025",
"meta": "CEN302 · Spring 2024–2025 · 21 Mayıs 2025 · Süre 1 saat · Dr. Mohammed Al-Hubaishi",
"intro": "Aşağıdaki sorular 2024–2025 final sınavından birebir alınmıştır (grafik/şekle dayalı birkaç soru sonda not edilmiştir). Şıkkı seçince doğru/yanlış durumu ve açıklama anında görünür; istersen işaretlemeden 'Cevabı Göster' ile direkt cevabı açabilirsin.",
"questions": [
 {"q":"Which statement about the memory requirements of BFS and DFS is correct?",
  "opts":["BFS typically requires less memory than DFS","BFS typically requires more memory than DFS","BFS and DFS have identical memory requirements","Memory depends only on graph size"],
  "correct":1,"exp":"BFS bir seviyedeki tüm komşuları kuyrukta tuttuğu için DFS'ten daha çok bellek harcar."},
 {"q":"What is the worst-case time complexity of both BFS and DFS?",
  "opts":["O(V·E)","O(V²)","O(V + E)","O(E²)"],
  "correct":2,"exp":"Her düğüm ve her kenar bir kez işlenir → O(V+E)."},
 {"q":"In the DP table for 0/1 knapsack, what do the rows and columns represent?",
  "opts":["Rows=values, cols=resources","Rows=weights, cols=values","Rows=items, columns=possible weights (capacities)","Both represent weights"],
  "correct":2,"exp":"0/1 knapsack DP tablosunda satırlar nesneleri, sütunlar olası kapasiteleri (ağırlıkları) temsil eder."},
 {"q":"Recurrence for DP[i][j] in the 0/1 Knapsack problem:",
  "opts":["DP[i][j] = DP[i-1][j]","DP[i][j] = max(DP[i-1][j], value[i] + DP[i-1][j - weight[i]])","DP[i][j] = DP[i-1][j] + value[i]","DP[i][j] = min(DP[i-1][j], value[i] + DP[i-1][j-weight[i]])"],
  "correct":1,"exp":"Her nesne için 'al' (value + kalan kapasite) ve 'alma' seçeneklerinin maksimumu alınır."},
 {"q":"Which is TRUE about the time complexity of the 0/1 knapsack DP solution?",
  "opts":["O(n·W)","O(n²)","O(W²)","O(n log W)"],
  "correct":0,"exp":"DP tablosu (n+1)×(W+1) boyutunda, her hücre O(1) → O(n·W) (pseudo-polynomial)."},
 {"q":"Which statement about logarithms is TRUE?",
  "opts":["log₂(n) grows faster than n","log₂(n) grows slower than n","log₂(n) = n² for all n","log₂(n) is always less than 1"],
  "correct":1,"exp":"Logaritma n'den çok daha yavaş büyür: 1 < log n < n."},
 {"q":"What happens if Bellman-Ford detects a negative cycle?",
  "opts":["It returns an error","It returns the shortest path","It ignores the cycle","It runs forever"],
  "correct":0,"exp":"V−1 turdan sonra hâlâ gevşetme mümkünse negatif çevrim vardır; algoritma hata döndürür (en kısa yol tanımsız)."},
 {"q":"The Bellman-Ford algorithm relaxes all edges:",
  "opts":["Once","V−1 times","E times","V times"],
  "correct":1,"exp":"En kısa yol en çok V−1 kenar içerir; bu yüzden tüm kenarlar V−1 kez gevşetilir → O(VE)."},
 {"q":"Why does BFS visit all nodes at the same level before moving to the next level?",
  "opts":["Because BFS follows the first-come-first-serve (FIFO) principle","Because BFS follows the last-in-first-out (LIFO) principle","Because BFS sorts nodes by vertex number first","Because it coincidentally processes them level by level"],
  "correct":0,"exp":"BFS queue (FIFO = first-come-first-serve) kullandığı için grafı seviye seviye gezer."},
 {"q":"Best data structure for implementing DFS recursively:",
  "opts":["Priority queue","Disjoint set","Stack","Queue"],
  "correct":2,"exp":"DFS recursion ile çalışır; recursion'ın çağrı yığını bir stack'tir (LIFO)."},
 {"q":"Which algorithm is better for the shortest path between two nodes in an UNWEIGHTED graph?",
  "opts":["Breadth-First Search (BFS)","Depth-First Search (DFS)","Both perform equally well","Neither can find shortest paths"],
  "correct":0,"exp":"BFS ağırlıksız grafikte en az kenarlı (en kısa) yolu garanti eder."},
 {"q":"Which of the following is NOT a step in Prim's algorithm?",
  "opts":["Sort all edges by weight","Initialize key values","Update key values for adjacent vertices","Pick the minimum-key vertex not in MST"],
  "correct":0,"exp":"Tüm kenarları ağırlığa göre sıralamak Kruskal'ın adımıdır, Prim'in değil."},
 {"q":"Which is NOT an application of the MCST algorithm?",
  "opts":["Network design","Resource allocation","Shortest path between two vertices","Transportation planning"],
  "correct":2,"exp":"İki düğüm arası en kısa yol Dijkstra/Bellman-Ford işidir; MST tüm düğümleri minimum toplam ağırlıkla bağlar."},
 {"q":"What does DP[i][j] represent in the 0/1 Knapsack DP solution?",
  "opts":["Whether item i should be included for weight j","The maximum profit using the first i items with weight limit j","The weight of item i when its value is j","The number of ways to achieve weight j"],
  "correct":1,"exp":"DP[i][j] = ilk i nesne ve kapasite j ile elde edilebilecek maksimum değer/kâr."},
 {"q":"Which statement is TRUE?",
  "opts":["Kruskal's algorithm always starts from the minimum-weight edge","Prim's algorithm always starts from the minimum-weight edge","Both always start from the minimum-weight edge","Neither starts from the minimum-weight edge"],
  "correct":0,"exp":"Kruskal kenarları sıralayıp en küçük ağırlıklı kenardan başlar. Prim keyfi bir düğümden başlar."},
 {"q":"If an algorithm has running time T(n) = 3n² + 2n + 5, its Big-O is:",
  "opts":["O(n)","O(n²)","O(n³)","O(2ⁿ)"],
  "correct":1,"exp":"Sabitler atılır, en yüksek dereceli terim kalır → O(n²)."},
 {"q":"Which is a distributed algorithm used in network routing?",
  "opts":["Dijkstra's algorithm","Bellman-Ford algorithm","Prim's algorithm","Kruskal's algorithm"],
  "correct":1,"exp":"Bellman-Ford dağıtık (distance-vector) yönlendirmede kolayca uygulanır; her düğüm yalnızca komşularıyla haberleşir."},
 {"q":"The running time of a nested loop where both loops run from 1 to n is:",
  "opts":["O(n log n)","O(n²)","O(n)","O(2ⁿ)"],
  "correct":1,"exp":"İç içe iki döngü n×n → O(n²)."},
 {"q":"Which is TRUE about the 0/1 Knapsack Problem?",
  "opts":["Items can be divided into fractions","Each item can be taken or left, but not divided","It can be solved greedily (optimally)","It is not an optimization problem"],
  "correct":1,"exp":"0/1'de her nesne ya tamamen alınır ya hiç alınmaz; bölünemez."},
 {"q":"If T(n) = T(n−1) + n, what is T(n)?",
  "opts":["O(n)","O(log n)","O(n²)","O(2ⁿ)"],
  "correct":2,"exp":"T(n) = n + (n−1) + … + 1 = n(n+1)/2 → O(n²)."},
 {"q":"Which algorithm is generally faster for DENSE graphs?",
  "opts":["Kruskal's algorithm","Prim's algorithm","Both are equal","Depends on the graph"],
  "correct":1,"exp":"Prim yoğun grafiklerde, Kruskal seyrek grafiklerde daha hızlıdır."},
 {"q":"Which step is UNIQUE to Kruskal's algorithm?",
  "opts":["Sorting all edges by weight","Using a priority queue","Starting from an arbitrary vertex","Updating key values"],
  "correct":0,"exp":"Kenarları ağırlığa göre sıralamak Kruskal'a özgüdür; key/priority queue Prim'de kullanılır."},
 {"q":"Which is NOT a characteristic of dynamic programming?",
  "opts":["Optimal substructure","Overlapping subproblems","Greedy choice property","Memoization"],
  "correct":2,"exp":"'Greedy choice property' greedy algoritmaların özelliğidir, DP'nin değil."},
 {"q":"Which algorithm can work on disconnected graphs to generate a forest?",
  "opts":["Kruskal's algorithm","Prim's algorithm","Both","Neither"],
  "correct":0,"exp":"Kruskal kopuk bileşenlerde de çalışır ve orman (forest) üretebilir; Prim bağlı grafik gerektirir."},
 {"q":"Time complexity of Prim's algorithm using a binary heap:",
  "opts":["O(V²)","O(E log V)","O(E²)","O(V log E)"],
  "correct":1,"exp":"Binary heap/öncelik kuyruğu ile Prim O(E log V)'dir (basit dizi ile O(V²))."},
 {"q":"Which traversal is used in web crawling to discover new pages?",
  "opts":["BFS","DFS","Both","Neither"],
  "correct":0,"exp":"BFS seviye seviye keşfederek yeni sayfaları bulur (web crawling)."},
 {"q":"Which traversal is guaranteed to find the shortest path in an unweighted graph?",
  "opts":["Dijkstra","BFS","DFS","Neither"],
  "correct":1,"exp":"Ağırlıksız grafikte en kısa yolu BFS garanti eder."},
 {"q":"Which data structure is essential for Kruskal's algorithm?",
  "opts":["Priority queue","Union-Find (Disjoint Set)","Stack","Queue"],
  "correct":1,"exp":"Kruskal çevrim tespitini Union-Find ile yapar."},
 {"q":"In the knapsack DP table, what does each cell represent?",
  "opts":["The number of items used","The minimum value for a given weight","The maximum value for a given weight and items considered","The total number of subproblems"],
  "correct":2,"exp":"Her hücre, o kapasite ve o ana kadarki nesnelerle elde edilebilecek maksimum değeri tutar."},
 {"q":"Which is TRUE about the greedy approach for 0/1 knapsack?",
  "opts":["It always gives the optimal solution","It may not give the optimal solution","It is always faster and optimal","It is the only way to solve it"],
  "correct":1,"exp":"0/1 knapsack'te greedy optimumu garanti etmez; DP gerekir."},
 {"q":"Which algorithm is optimal for the 0/1 knapsack problem?",
  "opts":["Divide and conquer","Greedy algorithm","Dynamic programming","Brute force only"],
  "correct":2,"exp":"0/1 knapsack DP ile O(nW) zamanda optimal çözülür."},
 {"q":"Which traversal is used in social network analysis to find communities/clusters?",
  "opts":["BFS","DFS","Both","Neither"],
  "correct":1,"exp":"Topluluk/cluster bulmada DFS kullanılır (derine inerek bileşenleri keşfeder)."},
 {"q":"Which of the following is NOT a valid use of BFS?",
  "opts":["Finding shortest path in unweighted graphs","Finding connected components","Topological sorting","Web crawling"],
  "correct":2,"exp":"Topolojik sıralama klasik olarak DFS/Kahn ile ilişkilendirilir; sınavın beklediği cevap budur. (Not: Kahn algoritması da BFS tabanlıdır.)"},
 {"q":"Which is FALSE about the knapsack problem?",
  "opts":["It is an NP-complete problem (0/1)","It can be solved using recursion","It can be solved using dynamic programming","It can always be solved in linear time"],
  "correct":3,"exp":"Knapsack lineer zamanda çözülemez; 0/1 DP'si O(nW)'dir."},
 {"q":"If a graph has negative edge weights but no negative cycles, which algorithm finds the shortest path?",
  "opts":["Dijkstra's algorithm","Bellman-Ford algorithm","Prim's algorithm","Kruskal's algorithm"],
  "correct":1,"exp":"Negatif kenarlarda Dijkstra çalışmaz; Bellman-Ford çalışır."},
 {"q":"Which is NOT a feature of Dijkstra's algorithm?",
  "opts":["Works with negative edge weights","Finds shortest path from a single source","Uses a priority queue","Faster for sparse graphs"],
  "correct":0,"exp":"Dijkstra negatif ağırlıklarla çalışmaz; bu onun bir özelliği DEĞİLDİR."},
 {"q":"Main difference between a simple module and a compound module in OMNeT++?",
  "opts":["Simple modules can contain other modules","Compound modules cannot send messages","Simple modules implement behavior; compound modules group modules","Compound modules are written in C++"],
  "correct":2,"exp":"Simple module davranışı C++ ile uygular; compound module başka modülleri gruplar (alt modüller içerir)."},
 {"q":"Which is a characteristic of Dynamic Programming?",
  "opts":["Solves problems by making greedy choices","Solves overlapping subproblems","Ignores previous solutions","Only works for sorting problems"],
  "correct":1,"exp":"DP örtüşen alt problemleri (overlapping subproblems) çözer ve sonuçları saklar."},
 {"q":"Which OMNeT++ class is the base for all simulation modules?",
  "opts":["cMessage","cPacket","cSimulation","cModule"],
  "correct":3,"exp":"cModule tüm modüllerin temel sınıfıdır (cSimpleModule ve cCompoundModule ondan türer)."},
 {"q":"Main difference between cMessage and cPacket in OMNeT++?",
  "opts":["There is no difference","cMessage is for packets, cPacket for timers","cPacket is for signals, cMessage for data","cPacket represents network packets (with length/fields); it extends cMessage"],
  "correct":3,"exp":"cPacket, cMessage'dan türeyen ve ağ paketlerini (uzunluk vb.) temsil eden sınıftır."},
 {"q":"Which is NOT a valid use of the par() function in OMNeT++?",
  "opts":["Accessing a module parameter","Setting/assigning a module parameter at runtime","Reading a parameter value","Using a parameter in calculations"],
  "correct":1,"exp":"par() parametreleri okumak/erişmek içindir; çalışma anında değer atamak onun amacı değildir."},
 {"q":"Which is NOT a property of the Greedy Method?",
  "opts":["Always finds the global optimum","Makes locally optimal choices","Works well for certain optimization problems","Does not reconsider previous choices"],
  "correct":0,"exp":"Greedy her zaman global optimumu bulmaz; bu bir özelliği DEĞİLDİR."},
 {"q":"Main difference between brute force and exhaustive search?",
  "opts":["Brute force is always faster","Brute force uses heuristics, exhaustive search does not","Exhaustive search reduces the space with optimizations","There is essentially no difference — both try all solutions"],
  "correct":3,"exp":"Brute-force ve exhaustive search pratikte aynı kavramdır: tüm olası çözümleri dener."},
 {"q":"Which is NOT a feature of the TicToc simulation in OMNeT++?",
  "opts":["Message passing between modules","Real-time data processing","Event scheduling","State variable tracking"],
  "correct":1,"exp":"TicToc ayrık olay (discrete event) simülasyonudur; gerçek-zamanlı (real-time) işleme yapmaz."},
 {"q":"Main purpose of using NED inheritance in OMNeT++?",
  "opts":["To reduce redundancy in network definitions","To increase simulation speed","To log simulation events","To terminate the simulation"],
  "correct":0,"exp":"NED kalıtımı, tekrar eden ağ/modül tanımlarını azaltmak (yeniden kullanım) içindir."},
 {"q":"Calculate T(n) for a symmetric-pair nested loop (i,j over n) — its Big-O class:",
  "opts":["O(n)","O(n log n)","O(n²)","O(2ⁿ)"],
  "correct":2,"exp":"İç içe iki döngü, sayım ≈ (n²−3n+2)/2 olsa da baskın terim n² → O(n²)."},
]
})

# ===========================================================================
# 2023–2024 FINAL (CEN302) — 24 Haziran 2024 — ~60 soru (kavramsal olanlar)
# ===========================================================================
EXAMS.append({
"id": "sinav2324",
"year": "2023–2024",
"meta": "CEN302 · Spring 2023–2024 · 24 Haziran 2024 · Süre 1 saat · Dr. Mohammed Al-Hubaishi",
"intro": "2023–2024 final sınavının kavramsal soruları (grafik/şekle dayalı yol-bulma soruları ayrıca özetlendi). Şıkkı seçince doğru/yanlış durumu ve açıklama anında görünür; istersen işaretlemeden 'Cevabı Göster' ile direkt cevabı açabilirsin.",
"questions": [
 {"q":"Which best describes the approach used in Kruskal's algorithm?",
  "opts":["Start empty and repeatedly add the most expensive edge without a cycle","Start with each vertex as its own tree, merge cheapest trees without a cycle","Start with all edges, remove the most expensive edge that doesn't disconnect","Start with edges sorted by weight and add the next cheapest edge that doesn't create a cycle"],
  "correct":3,"exp":"Kruskal: kenarları artan sırala, çevrim oluşturmayan en ucuz kenarı sırayla ekle (V−1 kenara kadar)."},
 {"q":"An algorithm processes data using a triple-nested loop. Which statement is best?",
  "opts":["Linear time, practical for large datasets","Quadratic time, practical for moderate datasets","Cubic time, practical for small problems only","Exponential time, never practical"],
  "correct":2,"exp":"Üç iç içe döngü → O(n³) (kübik); yalnızca küçük problemlerde pratiktir."},
 {"q":"The Pandas function to clean (drop) empty cells is:",
  "opts":["replace()","fillna()","dropna()","clean()"],
  "correct":2,"exp":"dropna() null içeren satırları kaldırır."},
 {"q":"The optimal solution in the Greedy Method has:",
  "opts":["Many solutions","One solution","One-to-many solutions","Both a and b"],
  "correct":1,"exp":"Optimal çözüm, feasible çözümler arasından seçilen tek (en iyi) çözümdür."},
 {"q":"What is the primary objective of an MCST in a connected, weighted graph?",
  "opts":["Find the shortest path between two vertices","Connect all vertices with the minimum total edge weight","Identify the vertex with the highest degree","Ensure no vertex has degree higher than 2"],
  "correct":1,"exp":"MST tüm düğümleri minimum toplam kenar ağırlığıyla, çevrimsiz bağlar."},
 {"q":"A minimum cost spanning tree is guaranteed to exist in:",
  "opts":["Graphs with positive edge weights only","Any connected graph","Any weighted graph","Any connected, weighted graph"],
  "correct":3,"exp":"MST için graf hem bağlı (connected) hem ağırlıklı (weighted) olmalıdır."},
 {"q":"Which algorithm can be used to find a minimum cost spanning tree?",
  "opts":["Dijkstra's algorithm","Bellman-Ford algorithm","Prim's algorithm","All of the above"],
  "correct":2,"exp":"MST için Prim (ve Kruskal) kullanılır; Dijkstra ve Bellman-Ford en kısa yol algoritmalarıdır."},
 {"q":"The Greedy Method is used for solving:",
  "opts":["NP-hard problems","Optimization problems","Only maximization problems","Sorting problems"],
  "correct":1,"exp":"Greedy, maksimum/minimum arayan optimizasyon problemleri içindir."},
 {"q":"Which is an advantage of using Dynamic Programming for the Knapsack Problem?",
  "opts":["It always yields the optimal solution","It uses far fewer resources than greedy","It can be easily parallelized","It works only for fractional knapsack"],
  "correct":0,"exp":"DP, 0/1 knapsack için her zaman optimal sonucu verir (greedy vermez)."},
 {"q":"Which best describes the GREEDY approach for the Knapsack Problem?",
  "opts":["Select items with the lowest value-to-weight ratio","Select items with the highest value-to-weight ratio","Randomly select items","Always select the heaviest items"],
  "correct":1,"exp":"Greedy (fractional) knapsack en yüksek value/weight oranlı nesneleri önce seçer."},
 {"q":"Which algorithm is commonly used to solve the (0/1) Knapsack Problem optimally?",
  "opts":["Breadth-first search","Depth-first search","Dynamic programming","Dijkstra's algorithm"],
  "correct":2,"exp":"0/1 knapsack DP ile optimal çözülür."},
 {"q":"In the Fractional Knapsack Problem, the strategy to maximize total value is:",
  "opts":["Include lowest value-to-weight ratio first","Include highest value-to-weight ratio first, possibly taking a part of the last item","Randomly select items","Always include the heaviest items first"],
  "correct":1,"exp":"En yüksek orandan başla; son nesne sığmazsa kesrini al."},
 {"q":"The main difference between Fractional and 0/1 Knapsack lies in:",
  "opts":["The maximum weight the knapsack can hold","The value of the items","Whether items can be partially included or not","The number of items available"],
  "correct":2,"exp":"Fractional'da nesne bölünebilir (kesir alınır); 0/1'de bölünemez."},
 {"q":"In the 0/1 Knapsack Problem, how is item inclusion decided?",
  "opts":["By weight only, regardless of value","Partially, based on value-to-weight ratio","Each item must be fully included or fully excluded","All items included; only weight distribution decided"],
  "correct":2,"exp":"0/1'de ikili karar: ya tamamen al ya hiç alma."},
 {"q":"Which best describes the Fractional Knapsack Problem?",
  "opts":["Each item is fully included or fully excluded","Items can be divided into fractions for partial inclusion","Only items of the same value can be partially included","No weight limit, but limited item count"],
  "correct":1,"exp":"Fractional'da nesneler kesirlere bölünüp kısmen alınabilir."},
 {"q":"What does Dijkstra's algorithm use to prevent revisiting / cycles?",
  "opts":["Kruskal's algorithm","Depth-First Search","Breadth-First Search","A list of visited nodes"],
  "correct":3,"exp":"Ziyaret edilen düğümler işaretlenir (visited set); kesinleşen düğüm bir daha işlenmez."},
 {"q":"In the context of an MCST, what does the term \"cycle\" refer to?",
  "opts":["A graph with an odd number of vertices","A graph with no edges","A path that starts and ends at the same vertex","A path that uses the same edge more than once"],
  "correct":2,"exp":"Çevrim (cycle): başladığı düğüme geri dönen bir yol. Kruskal çevrim oluşturacak kenarı atlar."},
 {"q":"Best statement about strengths of BFS vs DFS:",
  "opts":["BFS best for shortest path in unweighted graphs; DFS best for cycle detection / pathfinding","BFS best for shortest path in weighted graphs; DFS for unweighted","DFS best for shortest path; BFS for cycle detection","Both are identical in all use cases"],
  "correct":0,"exp":"BFS ağırlıksızda en kısa yol; DFS çevrim tespiti ve derin pathfinding için uygundur."},
 {"q":"What does Dijkstra's algorithm primarily compute?",
  "opts":["Shortest path from a source vertex to all other vertices in a weighted graph","The longest path between two nodes","Whether a graph is a tree","The number of vertices"],
  "correct":0,"exp":"Dijkstra tek kaynaktan tüm düğümlere en kısa yolları bulur (single-source shortest path)."},
 {"q":"Which characteristic makes a problem efficiently solvable by Dynamic Programming?",
  "opts":["Overlapping subproblems","Only one possible solution","Large input size","Linear time complexity"],
  "correct":0,"exp":"DP, örtüşen alt problemleri (overlapping subproblems) olan problemlerde verimlidir."},
 {"q":"What does the \"optimal substructure\" property mean?",
  "opts":["The optimal solution is built from optimal solutions of its subproblems","The solution is a sequence of random decisions","It can be retrieved from a hash table","The problem has only one solution"],
  "correct":0,"exp":"Optimal substructure: bütünün optimal çözümü, alt problemlerin optimal çözümlerini içerir."},
 {"q":"Time complexity of the naive recursive Fibonacci:",
  "opts":["O(2ⁿ)","O(1)","O(n log n)","O(n)"],
  "correct":0,"exp":"Naif özyinelemeli Fibonacci her çağrıda iki dala ayrılır → O(2ⁿ)."},
 {"q":"In DP, which approach avoids recalculating overlapping subproblems by storing results?",
  "opts":["Greedy approach","Top-down approach (memoization)","Divide and conquer","Brute force"],
  "correct":1,"exp":"Top-down (memoization) sonuçları saklayarak tekrarı önler. (Bottom-up/tabulation de aynı amaca hizmet eder.)"},
 {"q":"Which is NOT a step in the bottom-up DP approach?",
  "opts":["Storing subproblem solutions in a table","Starting from the smallest subproblems","Solving subproblems recursively","Building up in order to larger subproblems"],
  "correct":2,"exp":"Bottom-up (tabulation) iteratif tabloyla ilerler; özyineleme top-down'ın yöntemidir."},
 {"q":"Primary characteristic of greedy algorithms:",
  "opts":["Always guarantee the optimal solution","Require exhaustive search","Make locally optimal choices at each step","Have O(n²) time complexity"],
  "correct":2,"exp":"Greedy her adımda yerel (locally) optimal seçimi yapar."},
 {"q":"What does the \"greedy choice property\" entail?",
  "opts":["A locally optimal choice leads to the globally optimal solution","Decisions based on future information","Always backtracking to fix decisions","Exponential time complexity"],
  "correct":0,"exp":"Greedy choice property: yerel optimal seçimlerin global optimuma götürmesi."},
 {"q":"Which is TRUE about the Greedy Method?",
  "opts":["It requires DP for implementation","It guarantees optimality for all problems","It applies only to single-feasible-solution problems","It does not always produce the optimal solution, but it is efficient"],
  "correct":3,"exp":"Greedy her zaman optimal değildir ama verimlidir."},
 {"q":"Which distinguishes Greedy from Dynamic Programming?",
  "opts":["Greedy does not require memoization of subproblems","Greedy is always faster asymptotically","Greedy applies only to optimization problems","Greedy always finds the optimal solution"],
  "correct":0,"exp":"Greedy alt problem sonuçlarını saklamaz (memoization yok); DP saklar."},
 {"q":"Which is NOT a step in designing a Greedy algorithm?",
  "opts":["Identifying overlapping subproblems","Defining the objective function","Making a greedy choice","Proving correctness of the algorithm"],
  "correct":0,"exp":"Örtüşen alt problem belirlemek DP'nin adımıdır, greedy'nin değil."},
 {"q":"Which approach tries ALL possible solutions to find the optimal one?",
  "opts":["Dynamic Programming","Greedy Method","Divide-and-Conquer","Exhaustive Search"],
  "correct":3,"exp":"Exhaustive/Brute-force tüm olası çözümleri dener."},
 {"q":"Which approach breaks a problem into overlapping subproblems and uses memoization?",
  "opts":["Divide-and-Conquer","Dynamic Programming","Greedy Method","Brute-Force"],
  "correct":1,"exp":"Bu, Dynamic Programming'in tanımıdır."},
 {"q":"A search algorithm takes 10 ms for 100 files and scales logarithmically. ~Time for 1000 files?",
  "opts":["~100 ms, O(n·log)","~15–20 ms, O(log n): 10·log(1000)/log(100)","~100 ms, O(n)","~10 ms, O(1)"],
  "correct":1,"exp":"Yeni süre = eski · f(yeni)/f(eski) = 10·log(1000)/log(100) ≈ 10·1.5 ≈ 15 ms (logaritmik)."},
 {"q":"After df.fillna(135, inplace=True), what is true about the DataFrame?",
  "opts":["Same data, no NaN replaced","Modified in-place, all NaN values replaced by 135","A new column 'fillna' with 135 is added","It is deleted and reassigned"],
  "correct":1,"exp":"inplace=True orijinali değiştirir; tüm NaN'lar 135 ile dolar."},
 {"q":"print(new_df.to_string()) is used to:",
  "opts":["Print the first few rows","Convert to CSV and print the path","Print the ENTIRE DataFrame, including indices and column names","Print a statistical summary"],
  "correct":2,"exp":"to_string() tüm DataFrame'i (index ve sütun adlarıyla) yazdırır."},
 {"q":"What does dropna() do on a pandas DataFrame?",
  "opts":["Adds NaN to all rows","Deletes rows containing any NaN values","Deletes columns containing any NaN","Replaces NaN with the column mean"],
  "correct":1,"exp":"dropna() NaN içeren satırları siler."},
 {"q":"What does getName() return in Txc1::initialize() (TicToc)?",
  "opts":["The project name","The simple module's name (e.g. \"tic\"/\"toc\")","The message name","The class name"],
  "correct":1,"exp":"getName() modülün adını döndürür; tic mi toc mu olduğunu ayırt etmek için kullanılır."},
 {"q":"Which file contains the C++ implementation of the TicToc simulation?",
  "opts":["tictoc.ned","tictoc.cc","tictoc.h","omnetpp.ini"],
  "correct":1,"exp":".cc dosyası modül davranışını (C++) içerir; .ned yapı, .ini yapılandırma."},
 {"q":"To plot the results of a signal connected to a variable, which function is used?",
  "opts":["module()","send()","emit()","recordScalar()"],
  "correct":2,"exp":"emit(signal, value) sinyal üzerinden istatistik/çizim için değer yayar."},
 {"q":"What does send(msg, \"gate$o\", k) refer to ($o)?",
  "opts":["input","output","input/output","none"],
  "correct":1,"exp":"\"gate$o\" kapının çıkış (output) tarafıdır; \"$i\" giriş tarafıdır."},
 {"q":"Where does the output of EV << ... appear in OMNeT++?",
  "opts":["Print statements","Exception handling","Event logging (log window)","Memory management"],
  "correct":2,"exp":"EV, simülasyon olay log penceresine yazar (event logging)."},
 {"q":"What is the correct gate definition for the shown OMNeT++ connections?",
  "opts":["shout gate[];","inout gate[];","in gate++;","out gate++;"],
  "correct":1,"exp":"Çift yönlü (<-->) bağlantılar için 'inout gate[];' (vektör inout kapı) kullanılır."},
 {"q":"In the .ned file, the sample module should have the ____ name as in the .ned to simulate the scenario.",
  "opts":["Different name","Any name","Same name","No name"],
  "correct":2,"exp":"NED'deki modül adı ile C++ sınıfının/Define_Module adının aynı olması gerekir."},
 {"q":"When the counter variable reaches zero in the simulation, what happens?",
  "opts":["The simulation pauses","It resets the counter","It generates an error","It runs out of events and terminates"],
  "correct":3,"exp":"counter==0'da mesaj silinir, yeni olay üretilmez ve simülasyon biter."},
 {"q":"To keep track of a counter's value during the run, you would:",
  "opts":["Modify initialize() to display it","Use the WATCH macro to observe it","Use a breakpoint on each change","Print it to console each decrement"],
  "correct":1,"exp":"WATCH(counter) değişkeni GUI inspector'da izlenebilir yapar."},
 {"q":"What does the WATCH macro in a simulation module do?",
  "opts":["Terminates the simulation after a time","Observes variable values in the graphical runtime environment","Pauses the simulation at an event","Synchronizes across modules"],
  "correct":1,"exp":"WATCH bir değişkeni çalışma-zamanı GUI'sinde gözlemlenebilir kılar."},
 {"q":"How is the handleMessage() method invoked in TicToc models?",
  "opts":["Manually by the user","Automatically by the simulation kernel when a message arrives","Only at fixed time intervals","Never"],
  "correct":1,"exp":"handleMessage(), bir mesaj (dış veya self-message) geldiğinde simülasyon çekirdeği tarafından otomatik çağrılır."},
]
})

print("EXAMS loaded:", [(e["year"], len(e["questions"])) for e in EXAMS])
