# -*- coding: utf-8 -*-
# Cikmis final sinavlari. correct = dogru sikkin index'i (0=A).


def q(num, text, opts, correct, exp):
    return {"num": num, "q": text, "opts": opts, "correct": correct, "exp": exp}


EXAMS = []


# ===========================================================================
# 2024-2025 FINAL (CEN202) - 21/5/2025 - 50 soru
# ===========================================================================
EXAMS.append({
    "id": "sinav2425",
    "year": "2024-2025",
    "meta": "CEN202 · Spring 2024-2025 · 21/5/2025 · Time: H · Dr. Mohammed Al-Hubaishi",
    "intro": "2024-2025 final PDF'indeki sorular ayrica girildi. Sik secince dogru/yanlis ve aciklama aninda gorunur; istersen isaretlemeden 'Cevabi Goster' ile cevabi acabilirsin.",
    "questions": [
        q(1, "Which statement about the memory requirements of BFS and DFS is correct?",
          ["BFS typically requires less memory than DFS",
           "BFS typically requires more memory than DFS",
           "BFS and DFS have identical memory requirements",
           "Memory requirements depend only on the graph size, not the algorithm"],
          1, "BFS ayni seviyedeki cok sayida dugumu kuyrukta tutabildigi icin genelde DFS'ten daha fazla bellek kullanir."),
        q(2, "What is the worst-case time complexity of both BFS and DFS?",
          ["O(V*E)", "O(V)", "O(E)", "O(V+E)"],
          3, "Komşuluk listesiyle her dugum ve her kenar en fazla birkac kez islenir: O(V+E)."),
        q(3, "In the 0/1 Knapsack dynamic programming approach, what do the rows and columns of the DP table represent?",
          ["Rows represent possible values, columns represent elements",
           "Rows represent weights, columns represent values",
           "Rows represent elements (items), columns represent possible weights",
           "Both rows and columns represent different weights"],
          2, "Satirlar ilk i item'i, sutunlar ise kapasite/olasi agirlik limitini temsil eder."),
        q(4, "What is the recurrence relation for calculating DP[i][j] in the 0/1 Knapsack problem?",
          ["DP[i][j] = DP[i-1][j]",
           "DP[i][j] = max(DP[i-1][j], value[i] + DP[i-1][j-weight[i]])",
           "DP[i][j] = DP[i-1][j] + DP[i][j-1]",
           "DP[i][j] = min(DP[i-1][j], value[i] + DP[i-1][j-weight[i]])"],
          1, "Item alinmazsa DP[i-1][j], alinirsa value[i] + kalan kapasitenin en iyi degeri; maksimum secilir."),
        q(5, "Which of the following is TRUE about the time complexity of the 0/1 knapsack DP solution?",
          ["It is O(nW)", "It is O(n^2)", "It is O(W^2)", "It is O(n log W)"],
          0, "n item ve W kapasite icin tablo n*W hucrelidir."),
        q(6, "Which of the following statements about logarithms is TRUE?",
          ["log_2(n) grows faster than n.",
           "log_2(n) grows slower than n.",
           "log_2(n) = n^2 for all n.",
           "log_2(n) is always less than 1."],
          1, "Logaritmik buyume, dogrusal buyumeden daha yavastir."),
        q(7, "What happens if Bellman-Ford detects a negative cycle?",
          ["It returns an error", "It returns the shortest path", "It ignores the cycle", "It runs forever"],
          0, "Negatif cevrimde en kisa yol tanimsiz hale gelir; Bellman-Ford bunu hata/uyari olarak bildirir."),
        q(8, "The Bellman-Ford algorithm relaxes all edges:",
          ["Once", "V-1 times", "E times", "V times"],
          1, "En kisa basit yol en fazla V-1 kenar icerir."),
        q(9, "Why does BFS visit all nodes at the same level (distance from source) before moving to the next level in the lecture code?",
          ["Because BFS uses a concept that follows the first-come-first-serve principle.",
           "Because BFS uses a concept that follows the last-in-first-out principle.",
           "Because BFS sorts nodes by their vertex number before processing them.",
           "Because BFS uses concept in order, coincidentally processes them level by level"],
          0, "BFS kuyruk/FIFO mantigi ile calisir; once eklenen dugum once islenir."),
        q(10, "Which of the following is the best data structure for implementing DFS recursively?",
          ["Priority queue", "Disjoint set", "Stack", "Queue"],
          2, "Recursive DFS, cagri yigini sayesinde stack davranisi gosterir."),
        q(11, "Which algorithm is better suited for finding the shortest path between two nodes in an unweighted graph?",
          ["Breadth-First Search (BFS)", "Depth-First Search (DFS)", "Both BFS and DFS perform equally well", "Neither BFS nor DFS can find shortest paths"],
          0, "Ağırliksiz grafikte BFS seviye seviye ilerledigi icin en az kenarli yolu garanti eder."),
        q(12, "Which of the following is NOT a step in Prim's algorithm?",
          ["Sort all edges by weight", "Initialize key values", "Update key values for adjacent vertices", "Pick the minimum key vertex not in MST"],
          0, "Tum kenarlari siralamak Kruskal'in tipik adimidir."),
        q(13, "Which of the following is NOT an application of MCST algorithms?",
          ["Network design", "Resource allocation", "Shortest path in weighted graphs", "Transportation planning"],
          2, "Shortest path problemi Dijkstra/Bellman-Ford ile cozulur; MCST tum dugumleri minimum toplam maliyetle baglar."),
        q(14, "What does the state DP[i][j] represent in the 0/1 Knapsack dynamic programming solution?",
          ["Whether item i should be included to achieve weight j",
           "The maximum profit when using first i items with a weight limit of j",
           "The weight of item i when its value is j",
           "The number of ways to achieve weight j using i items"],
          1, "DP[i][j], ilk i item ve j kapasiteyle elde edilebilen maksimum kari tutar."),
        q(15, "Which of the following statements is TRUE?",
          ["Kruskal's algorithm always starts from the minimum weight edge",
           "Prim's algorithm always starts from the minimum weight edge",
           "Both always start from the minimum weight edge",
           "Neither starts from the minimum weight edge"],
          0, "Kruskal kenarlari artan agirlikla isler; Prim keyfi bir dugumden baslayabilir."),
        q(16, "If an algorithm has a running time of T(n) = 3n^2 + 3n + 3, what is its Big O complexity?",
          ["O(log n)", "O(n)", "O(n^2)", "O(n^3)"],
          2, "En buyuk dereceli terim n^2 oldugu icin Big-O O(n^2)'dir."),
        q(17, "Which is a distributed algorithm used in network routing?",
          ["Dijkstra's algorithm", "Bellman-Ford algorithm", "Prim's algorithm", "Kruskal's algorithm"],
          1, "Distance-vector routing mantigi Bellman-Ford'a dayanir."),
        q(18, "The running time of a nested loop where both loops run from 1 to n is:",
          ["O(n log n)", "O(log n)", "O(n)", "O(n^2)"],
          3, "n kez calisan dis dongu ve n kez calisan ic dongu toplam n*n is yapar."),
        q(19, "Which of the following is TRUE about the 0/1 Knapsack Problem?",
          ["Items can be divided into fractions", "Each item can be taken or left, but not divided", "It can be solved greedily", "It is not an optimization problem"],
          1, "0/1 knapsack'te her item ya tamamen alinir ya hic alinmaz."),
        q(20, "If T(n) = T(n-1) + c, what is T(n)?",
          ["O(n)", "O(log n)", "O(n^2)", "O(2^n)"],
          0, "Her adim sabit c ekler ve n adim vardir: O(n)."),
        q(21, "Which algorithm is generally faster for dense graphs?",
          ["Kruskal's algorithm", "Prim's algorithm", "Both are equal", "Depends on the graph"],
          1, "Yogun grafiklerde Prim genellikle daha uygundur."),
        q(22, "Which step is unique to Kruskal's algorithm?",
          ["Sorting all edges by weight", "Using a priority queue", "Starting from an arbitrary vertex", "Updating key values"],
          0, "Kruskal kenarlari agirligina gore siralayarak baslar."),
        q(23, "Which of the following is NOT a characteristic of dynamic programming?",
          ["Optimal substructure", "Overlapping subproblems", "Greedy choice property", "Memoization"],
          2, "Greedy choice property greedy algoritmalarin ozelligidir."),
        q(24, "Which algorithm can work on disconnected graphs to generate a forest?",
          ["Kruskal's algorithm", "Prim's algorithm", "Both", "Neither"],
          0, "Kruskal her bilesende MST olusturarak forest uretebilir."),
        q(25, "The time complexity of Prim's algorithm using a binary heap is:",
          ["O(V^2)", "O(E log V)", "O(E^2)", "O(V log E)"],
          1, "Binary heap ile Prim O(E log V) kabul edilir."),
        q(26, "Which traversal is used in web crawling to discover new pages?",
          ["BFS", "DFS", "Both", "Neither"],
          0, "Web crawling'de sayfalar genellikle seviye seviye kesfedilir."),
        q(27, "Which traversal is guaranteed to find the shortest path in an unweighted graph?",
          ["Dijkstra", "BFS", "DFS", "Neither"],
          1, "BFS agirliksiz grafikte en kisa kenar sayisini garanti eder."),
        q(28, "Which data structure is essential for Kruskal's algorithm?",
          ["Priority queue", "Union-Find", "Stack", "Queue"],
          1, "Union-Find, cevrim olusup olusmadigini hizli kontrol eder."),
        q(29, "In the DP table for knapsack, what does each cell represent?",
          ["The number of items used",
           "The minimum value for a given weight",
           "The maximum value for a given weight and items considered",
           "The total number of subproblems"],
          2, "Her hucre, o kapasite ve o ana kadar dusunulen itemlerle maksimum degeri tutar."),
        q(30, "Which of the following is TRUE about the greedy approach for 0/1 knapsack?",
          ["It always gives the optimal solution", "It may not give the optimal solution", "It is faster than DP", "It is the only way to solve it"],
          1, "0/1 knapsack icin greedy optimumu garanti etmez."),
        q(31, "Which algorithm is optimal for the 0/1 knapsack problem?",
          ["Divide and conquer", "Greedy algorithm", "Dynamic programming", "Brute force only"],
          2, "0/1 knapsack'in standart optimal cozumu dynamic programming'dir."),
        q(32, "Which traversal is used in social network analysis to find communities?",
          ["BFS", "DFS", "Both", "Neither"],
          1, "Sınav bağlamında topluluk/bilesen kesfi DFS ile eslestirilmis."),
        q(33, "Which of the following is NOT a valid use of BFS?",
          ["Finding shortest path in unweighted graphs", "Finding connected components", "Topological sorting", "Web crawling"],
          2, "Topological sorting klasik olarak DFS veya Kahn algoritmasi ile anlatilir; burada beklenen cevap budur."),
        q(34, "Which of the following is FALSE about the knapsack problem?",
          ["It is an NP-complete problem", "It can be solved using recursion", "It can be solved using dynamic programming", "It can always be solved in linear time"],
          3, "Knapsack her zaman lineer zamanda cozulmez."),
        q(35, "If a graph has negative edge weights but no negative cycles, which algorithm is guaranteed to find the shortest path?",
          ["Dijkstra's algorithm", "Bellman-Ford algorithm", "Prim's algorithm", "Kruskal's algorithm"],
          1, "Bellman-Ford negatif kenarlarla calisabilir, negatif cycle yoksa sonucu verir."),
        q(36, "Which of the following is NOT a feature of Dijkstra's algorithm?",
          ["Works with negative edge weights", "Finds shortest path from a single source", "Uses a priority queue", "Faster for sparse graphs"],
          0, "Dijkstra negatif agirlikli kenarlar icin garanti vermez."),
        q(37, "What is the main difference between a simple module and a compound module in OMNeT++?",
          ["Simple modules can contain other modules", "Compound modules cannot send messages", "Simple modules implement behavior; compound modules group modules", "Compound modules are written in C++"],
          2, "Simple module davranis kodunu uygular; compound module alt modulleri gruplar."),
        q(38, "Which of the following is a characteristic of Dynamic Programming?",
          ["Solves problems by making greedy choices", "Solves overlapping subproblems", "Ignores previous solutions", "Only works for sorting problems"],
          1, "DP, overlapping subproblems sonucunu saklayarak tekrar hesaplamayi azaltir."),
        q(39, "Which OMNeT++ class is the base for all simulation modules?",
          ["cMessage", "cPacket", "cSimulation", "cModule"],
          3, "OMNeT++ modulleri cModule tabanindan gelir."),
        q(40, "What is the main difference between cMessage and cPacket in OMNeT++?",
          ["There is no difference",
           "cMessage is for network packets, cPacket is for timers",
           "cPacket is for control signals, cMessage is for data",
           "cPacket can encapsulate other messages, cMessage cannot"],
          3, "cPacket, cMessage'in paket odakli turevidir ve paket/encapsulation ozellikleri tasir."),
        q(41, "Which of the following is NOT a valid use of the par() function in OMNeT++?",
          ["Accessing a module parameter", "Setting a module parameter", "Reading a parameter value", "Using a parameter in calculations"],
          1, "par() parametreye erisim/okuma icindir; soruda beklenen gecersiz kullanim set etmektir."),
        q(42, "Which of the following is NOT a property of the Greedy Method?",
          ["Always finds the global optimum", "Makes locally optimal choices", "Works well for certain optimization problems", "Does not reconsider previous choices"],
          0, "Greedy her problemde global optimumu garanti etmez."),
        q(43, "What is the main difference between brute force and exhaustive search?",
          ["Brute force is always faster",
           "Brute force uses heuristics, exhaustive search does not",
           "Exhaustive search may use optimizations to reduce search space",
           "There is no difference"],
          3, "Bu ders baglaminda ikisi de tum olasiliklari deneme fikrini ifade eder."),
        q(44, "Which of the following is NOT a feature of the TicToc simulation in OMNeT++?",
          ["Message passing between modules", "Real-time data processing", "Event scheduling", "State variable tracking"],
          1, "TicToc ayrik olay simülasyonudur; real-time data processing ozelligi degildir."),
        q(45, "What is the main purpose of using NED inheritance in OMNeT++?",
          ["To reduce redundancy in network definitions", "To increase simulation speed", "To log simulation events", "To terminate the simulation"],
          0, "NED inheritance ortak tanimlari tekrar yazmadan kullanmak icindir."),
        q(46, "Where is the start node in this graph?",
          ["5", "1", "2", "7"],
          1, "PDF'teki grafikte beklenen baslangic dugumu 1 olarak okunuyor."),
        q(47, "Using Dijkstra's algorithm and read the network from graph, what is the path from node 0 to node 5?",
          ["0 9 7 8 3 4 5", "0 1 2 3 4 5", "0 1 4 5", "0 9 2 3 4 5"],
          0, "Kod/graf agirliklarina gore en dusuk maliyetli yol 0-9-7-8-3-4-5 olur."),
        q(48, "Calculate T(n) using summation equation?",
          ["(n^2-3n+2)/2", "(n^3-2n+2)/2", "(n^3-3n+2)/2", "(n^2-3n+2)^3/2"],
          0, "Dongu sayisi sum_{i=1}^{n-2}(n-i-1) = (n-2)(n-1)/2 = (n^2-3n+2)/2."),
        q(49, "Using Dijkstra's algorithm what are the values of node 4 resulting from update function?",
          ["Inf, 11,9", "Inf,3,4", "Inf,9,8", "Inf,8,9"],
          2, "Node 4 once sonsuz, sonra 2 uzerinden 9, daha sonra 5 uzerinden 8'e iner."),
        q(50, "Find the start node and what is this algorithm in the graph?",
          ["Kruskal's Algorithm", "Depth-First Search", "Breadth-First Search", "Dijkstra's algorithm"],
          2, "Sekil seviye seviye genisleyen BFS agacini gosterir; baslangic dugumu 1'dir."),
    ],
})


# ===========================================================================
# 2023-2024 FINAL (CEN202) - 24/6/2024 - PDF'teki okunabilir 57 soru
# ===========================================================================
EXAMS.append({
    "id": "sinav2324",
    "year": "2023-2024",
    "meta": "CEN202 · Spring 2023-2024 · 24/6/2024 · Time: 1h · Dr. Mohammed Al-Hubaishi",
    "intro": "2023-2024 final PDF'indeki gorunur sorular PDF yilindan ayrilmadan girildi. PDF dosyasinda Q8'den sonra okunur kisim Q12'ye atladigi icin orijinal Q numaralari rozetlerde korundu.",
    "questions": [
        q(1, "Kruskal's algorithm is used to find the Minimum Cost Spanning Tree (MCST) of a graph. Which of the following best describes the approach used by Kruskal's algorithm?",
          ["It starts with an empty graph and repeatedly adds the most expensive edge that does not create a cycle until all vertices are connected.",
           "It starts with each vertex as its own tree and repeatedly merges the two cheapest trees that can be joined without creating a cycle until there is only one tree.",
           "It starts with all edges included and repeatedly removes the most expensive edge that does not disconnect the graph until only the MCST remains.",
           "It starts with the edges sorted by weight and repeatedly adds the next cheapest edge that does not create a cycle until all vertices are connected."],
          3, "Kruskal kenarlari agirlik sirasina koyar ve cevrim olusturmayan en ucuz kenarlari ekler."),
        q(2, "An algorithm processes triples of data items using a triple-nested loop. Based on this information, which of the following statements best describes the algorithm's efficiency and practicality?",
          ["The algorithm has a linear running time and is practical for large datasets.",
           "The algorithm has a quadratic running time and is practical for moderate-sized datasets.",
           "The algorithm has a cubic running time and is practical for small problems only.",
           "The algorithm has an exponential running time and is generally not practical for any dataset size."],
          2, "Uc ic ice dongu tipik olarak O(n^3) calisir."),
        q(3, "Where is the start node in this graph?",
          ["1", "2", "5", "7"],
          0, "PDF'teki grafikte beklenen baslangic dugumu 1 olarak okunuyor."),
        q(4, "The function from Pandas Lib in Python to clean the empty cells is ______.",
          ["inplace()", "fillna()", "dropna()", "clean()"],
          2, "dropna(), eksik deger iceren satirlari varsayilan olarak kaldirir."),
        q(5, "The optimal solution in Greedy Method has ______.",
          ["many Solutions", "one solution", "one to many Solutions", "both a and b"],
          1, "Optimal cozum, uygun cozumler arasindaki tek en iyi secim olarak kabul edilir."),
        q(6, "What is the primary objective of finding a minimum cost spanning tree (MCST) in connected, weighted graph?",
          ["To find the shortest path between two specific vertices",
           "To connect all vertices with the minimum total weight of edges",
           "To identify the vertex with the highest degree",
           "To ensure that no vertex has a degree higher than 2"],
          1, "MCST tum dugumleri minimum toplam kenar maliyetiyle baglar."),
        q(7, "A minimum cost spanning tree is guaranteed to exist in:",
          ["Graphs with positive edge weights only", "Any connected graph", "Any weighted graph", "Any connected, weighted graph"],
          3, "Spanning tree icin baglilik, minimum cost icin agirlik bilgisi gerekir."),
        q(8, "Which of the following algorithms can be used to find a minimum cost spanning tree?",
          ["Dijkstra's algorithm", "Bellman-Ford algorithm", "Prim's algorithm", "All of the above"],
          2, "Prim minimum cost spanning tree algoritmasidir."),
        q(12, "Using Dijkstra's algorithm and read the network from graph, what is the path from node 0 to node 5?",
          ["0 1 2 3 4 5", "0 1 4 5", "0 9 2 3 4 5", "0 9 7 8 3 4 5"],
          3, "En dusuk maliyetli yol 0-9-7-8-3-4-5 olarak cikar."),
        q(13, "The Greedy Method is used for solving ______.",
          ["NP hard problems", "optimization problems", "Min problems", "Max problems"],
          1, "Greedy yontem optimizasyon problemlerinde kullanilir."),
        q(14, "From the following graph find the path using BFS and start from node 1?",
          ["1, 2, 4, 5,10, 3,8,7,6,9,11",
           "1,2,8,7,4,5,10,3,6,9,11",
           "1,2,10,3,8,6,7,9,4,11,5",
           "1,4,2,10,3,8,6,7,9,4,11,5"],
          0, "BFS start node 1'den seviye seviye ilerler; PDF'teki siralamaya uyan secenek A'dir."),
        q(15, "Which of the following is an advantage of using dynamic programming to solve the Knapsack Problem?",
          ["It always yields the optimal solution",
           "It requires significantly less computational resources than greedy algorithms",
           "It can be easily parallelized",
           "It works only for 0/1 Knapsack Problem"],
          0, "DP, 0/1 knapsack icin optimal sonucu garanti eder."),
        q(16, "Which of the following best describes the greedy algorithm approach for solving the Knapsack Problem?",
          ["Select items based on their lowest value-to-weight ratio",
           "Select items based on their highest value-to-weight ratio",
           "Randomly select items",
           "Always select the heaviest items"],
          1, "Greedy knapsack'te value/weight orani yuksek itemler once secilir."),
        q(17, "Which of the following algorithms is commonly used to solve the Knapsack Problem?",
          ["Breadth-first search", "Depth-first search", "Dynamic programming", "Dijkstra's algorithm"],
          2, "0/1 knapsack'in standart yontemi dynamic programming'dir."),
        q(18, "Given a knapsack capacity of 70 kg and the items listed in the image, what is the total maximum value that can be obtained, and which items are included in the optimal solution?",
          ["Total Value = 215, Items = Gold, Copper, Silver",
           "Total Value = 240, Items = Gold, Copper, Bronze",
           "Total Value = 245, Items = Gold, Silver, Bronze",
           "Total Value = 260, Items = Gold, Copper, Silver, Bronze"],
          3, "PDF'teki seceneklere gore beklenen maksimum deger D secenegidir."),
        q(19, "In solving the Fractional Knapsack Problem, what strategy is often used to maximize the total value of items in the knapsack?",
          ["Including items with the lowest value-to-weight ratio first.",
           "Including items with the highest value-to-weight ratio first and possibly taking a part of the last item.",
           "Randomly selecting items to include.",
           "Always include the heaviest items first."],
          1, "Fractional knapsack'te en yuksek value/weight orani once alinir."),
        q(20, "The main difference between the Fractional Knapsack Problem and the 0/1 Knapsack Problem lies in:",
          ["The maximum weight the knapsack can hold", "The value of the items", "Whether items can be partially included or not", "The number of items available"],
          2, "Fractional'da item bolunebilir; 0/1'de bolunemez."),
        q(21, "In the 0/1 Knapsack Problem, how is the decision made regarding the inclusion of items?",
          ["Items are included based on their weight, regardless of their value.",
           "Items can be partially included based on their value-to-weight ratio.",
           "Each item must be either fully included or fully excluded; partial inclusion is not allowed.",
           "All items must be included, and the problem is to determine the optimal distribution of weight among them."],
          2, "0/1 karari item'i tamamen almak veya tamamen disarida birakmaktir."),
        q(22, "Which of the following statements best describes the Fractional Knapsack Problem?",
          ["Each item must be either fully included or fully excluded from the knapsack.",
           "Items can be divided into fractions, allowing for partial inclusion in the knapsack.",
           "Only items of the same value can be partially included in the knapsack.",
           "The knapsack has no weight limit, but only a limited number of items can be included."],
          1, "Fractional knapsack itemlerin kesirli alinmasina izin verir."),
        q(23, "What is the correct definition of gates as the following Omnet++ code?",
          ["inout gate[];", "inout gate++;", "in gate++;", "out gate++;"],
          0, "gate++ kullanan cift yonlu baglantilar icin gate vektoru inout gate[] olarak tanimlanir."),
        q(24, "What is the output of the following code snippet? char msgname[20]; sprintf(msgname, \"tic-%d-to-%d\", src, dest);",
          ["Print variables src and dest", "Print msgname as a text", "Print the variable src and dest inside a text", "Print all 3 variables using the 2 conversion specifiers"],
          2, "sprintf, src ve dest degerlerini bicimlendirilmis metnin icine yazar."),
        q(25, "What does the iloc function do?",
          ["Filter output using python list comprehension", "Filter output using c++ list comprehension", "Add new columns to table", "Add new rows to table"],
          0, "iloc pandas'ta konuma dayali secim/filtreleme icin kullanilir; secenekler icinde buna en yakin ifade A'dir."),
        q(26, "What is the following python code doing? import pandas as pd; df = pd.read_csv('data.csv'); for x in df.index: if df.loc[x, 'Duration'] > 120: df.loc[x, 'Duration'] = 120",
          ["Replacing values", "Removing values", "Comparing values", "Cleaning values"],
          0, "Kod 120'den buyuk Duration degerlerini 120 ile degistirir."),
        q(27, "Using Dijkstra's algorithm what are the values of node 4 resulting from update function?",
          ["Inf, 11,9", "Inf,3,4", "Inf,9,8", "Inf,8,9"],
          2, "Node 4'un gecici degeri sonsuzdan 9'a, sonra 8'e guncellenir."),
        q(28, "In the context of a minimum cost spanning tree, what does the term 'cycle' refer to?",
          ["A graph with an odd number of vertices", "A graph with no edges", "A path that starts and ends at the same vertex", "A path that uses the same edge more than once"],
          2, "Cycle, basladigi dugume geri donen yoldur."),
        q(29, "A file searching algorithm takes 10 milliseconds to search a folder containing 100 files. Assuming the search time grows logarithmically with the number of files, approximately how long would it take to search a folder containing 1000 files?",
          ["O(n*n) -> T(n) = (10 milliseconds * 1000) * 10 / 100 = 100 milliseconds",
           "O(log n) -> T(n) = 10 milliseconds * log2(1000) / log2(100) = 20 milliseconds",
           "O(n) -> T(n) = (10 milliseconds * 1000) / 100 = 100 milliseconds",
           "O(1) -> T(n) = 10 milliseconds"],
          1, "PDF'te logaritmik buyume icin beklenen secenek B olarak verilmis."),
        q(30, "After executing `dataframe.fillna(135, inplace=True)`, what can be said about the DataFrame `dataframe`?",
          ["It contains the same data as before, with no NaN values replaced.",
           "It has been modified in-place, with all NaN values replaced by 135.",
           "It has a new column named 'fillna' with the value 135 for all rows that originally had NaN values.",
           "It has been deleted and a new DataFrame with filled NaN values has been assigned to the variable `dataframe`."],
          1, "inplace=True orijinal DataFrame'i degistirir ve NaN degerlerini 135 ile doldurur."),
        q(31, "The line `print(new_df.to_string())` in the code snippet is used to:",
          ["Print the first few rows of the DataFrame `new_df`.",
           "Convert the DataFrame `new_df` to a CSV file and print the file path.",
           "Print the entire DataFrame `new_df`, including indices and column names.",
           "Print the statistical summary of the DataFrame `new_df`."],
          2, "to_string() tum DataFrame'i metin olarak yazdirir."),
        q(32, "What does the `dropna()` method do when applied to a pandas DataFrame?",
          ["Adds NaN values to all rows",
           "Deletes rows containing any NaN values",
           "Deletes columns containing any NaN values",
           "Replaces NaN values with the mean of their respective columns"],
          1, "dropna() varsayilan olarak NaN iceren satirlari siler."),
        q(33, "Which approach tries all possible solutions to find the optimal one?",
          ["Dynamic Programming", "Greedy Method", "Divide-and-Conquer", "Exhaustive Search"],
          3, "Exhaustive search tum olasi cozumleri dener."),
        q(34, "Which approach breaks down a problem into overlapping subproblems, solves them recursively with memoization to avoid redundant calculations?",
          ["Divide-and-Conquer", "Dynamic Programming", "Greedy Method", "Brute-Force/Exhaustive Search"],
          1, "Overlapping subproblems + memoization dynamic programming'in tanimidir."),
        q(35, "Breadth-First Search (BFS) and Depth-First Search (DFS) are two fundamental graph traversal algorithms. Which of the following statements best describes the strengths and weaknesses of BFS and DFS?",
          ["BFS is better suited for finding the shortest path between two nodes in an unweighted graph, while DFS is better suited for detecting cycles in a graph and for finding a path between two nodes in a weighted graph.",
           "BFS is better suited for finding the shortest path between two nodes in a weighted graph, while DFS is better suited for detecting cycles in an unweighted graph.",
           "BFS is better suited for detecting cycles in a graph, while DFS is better suited for finding the shortest path between two nodes in a weighted graph.",
           "BFS is better suited for finding the longest path between two nodes in an unweighted graph, while DFS is better suited for detecting connected components in a weighted graph."],
          0, "BFS agirliksiz grafikte en kisa yol icin, DFS ise derin arama/cevrim tespiti icin uygundur."),
        q(36, "The name of the simple module in the .ned file should be the ______ name in the .cc file to simulate the behavior of the scenario in the OMNeT++'s project.",
          ["Different name", "Any name", "Same name", "No name"],
          2, "NED modulu ile C++ modul sinifi eslesmelidir."),
        q(37, "In the initialize function, what does getName() mean?",
          ["To get the project name", "To get the simple module name", "To get the message name", "To get the class name"],
          1, "getName() modulun adini dondurur."),
        q(38, "Which file contains the C++ implementation of the TicToc simulation?",
          ["tictoc.ned", "tictoc.cc", "tictoc.h", "omnetpp.ini"],
          1, ".cc dosyasi C++ implementasyonunu icerir."),
        q(39, "In order to plot the results of a signal connected to our variable, we use the function:",
          ["sceduleAt()", "send()", "emit()", "all of the above"],
          2, "OMNeT++ sinyal sonucunu kaydetmek/gostermek icin emit() kullanilir."),
        q(40, "What does send(msg, \"gate$i\", k) mean?",
          ["input", "output", "input/output", "none of the above"],
          0, "\"$i\" gate'in input tarafini belirtir."),
        q(41, "Where is the output of EV << ... in OMNeT++?",
          ["Print statements", "Exception handling", "Event logging", "Memory management"],
          2, "EV ciktilari OMNeT++ event log penceresine gider."),
        q(42, "In TicToc simulations, what is the role of the timeout message?",
          ["To reset the simulation clock", "To terminate the simulation", "To periodically trigger self-messages", "To simulate packet transmission delays"],
          2, "Timeout self-message'i belirli zamanlarda tekrar olay tetiklemek icindir."),
        q(43, "In TicToc simulations, what does the arrived signal indicate?",
          ["Packet reception at the destination node", "Packet departure from the source node", "Packet transmission failure", "Simulation initialization completion"],
          0, "arrived sinyali paketin hedefe ulasmasini temsil eder."),
        q(44, "How is the handleMessage() method invoked in TicToc modules?",
          ["Upon receiving an external interrupt", "Automatically by the simulation kernel", "Manually triggered by the user", "Periodically at fixed time intervals"],
          1, "Mesaj geldiginde OMNeT++ simulation kernel handleMessage() metodunu cagirir."),
        q(45, "Which function is used to set the duration of the next timeout event in TicToc simulation?",
          ["setDuration()", "setTimer()", "setTimeout()", "setInterval()"],
          2, "PDF'teki secenekler icinde beklenen fonksiyon setTimeout() olarak verilmis."),
        q(46, "What is the correct option when we send packets as the following codes? int k = intuniform(0, n-1); send(msg, \"gate$o\", k);",
          ["tic[0].gate++ <--> Channel <--> tic[1].gate++;",
           "tic[0].out++ --> Channel --> tic[1].in++;",
           "tic[0].in++ <-- Channel <-- tic[1].out++;",
           "tic[0].gate+ <--> Channel <--> tic[1].gate+;"],
          1, "\"gate$o\" output tarafindan gonderimdir; karsi modulun input kapisina gider."),
        q(47, "Which of the following is a characteristic of problems that can be solved efficiently using Dynamic Programming?",
          ["They have overlapping subproblems", "They have only one possible solution", "They have a large input size", "They have a linear time complexity"],
          0, "DP icin temel isaret overlapping subproblems ozelligidir."),
        q(48, "In Dynamic Programming, what does the \"optimal substructure\" property mean?",
          ["The problem can be broken down into smaller subproblems",
           "The solution can be represented as a sequence of decisions",
           "The solution can be efficiently retrieved using a hash table",
           "The problem has only one possible solution"],
          0, "Optimal cozum alt problemlerin cozumleri uzerinden kurulabildigi icin secenek A beklenir."),
        q(49, "What is the time complexity of the naive recursive approach for Fibonacci sequence calculation?",
          ["O(2^n)", "O(1)", "O(n log n)", "O(n!)"],
          0, "Naive Fibonacci iki dala ayrilan tekrarli cagri agaci uretir."),
        q(50, "In Dynamic Programming, which approach is used to avoid recalculating solutions of overlapping subproblems?",
          ["Greedy approach", "Top-down approach", "Bottom-up approach", "Divide and conquer approach"],
          1, "Top-down approach memoization ile tekrar hesaplamayi onler."),
        q(51, "Which of the following is NOT a step in solving a problem using the Bottom-up Dynamic Programming approach?",
          ["Storing solutions of subproblems in a table", "Starting from the smallest subproblem", "Solving subproblems recursively", "Iterating in a specific order to solve larger subproblems"],
          2, "Bottom-up iteratif tablo doldurur; recursive cozum top-down'a aittir."),
        q(52, "What is the primary characteristic of algorithms designed using the Greedy Method?",
          ["They always guarantee the optimal solution", "They require exhaustive search of all possible solutions", "They make locally optimal choices at each step", "They have a time complexity of O(n^2)"],
          2, "Greedy her adimda yerel olarak en iyi secimi yapar."),
        q(53, "In Greedy algorithms, what does the \"greedy choice property\" entail?",
          ["It guarantees that the locally optimal choice leads to the globally optimal solution", "It involves making decisions based on future information", "It always requires backtracking to correct previous choices", "It leads to exponential time complexity"],
          0, "Greedy choice property, yerel optimum secimlerin global optimuma goturmesini ifade eder."),
        q(54, "Which of the following statements is true about the Greedy Method?",
          ["It requires dynamic programming for implementation", "It guarantees the optimal solution for all types of problems", "It can only be applied to problems with a single feasible solution", "It does not always produce the optimal solution, but it is efficient"],
          3, "Greedy hizlidir ama her problemde optimal sonucu garanti etmez."),
        q(55, "Which characteristic distinguishes Greedy algorithms from Dynamic Programming?",
          ["Greedy algorithms do not require memorization of subproblems", "Greedy algorithms are faster in terms of time complexity", "Greedy algorithms are only applicable to optimization problems", "Greedy algorithms always find the optimal solution"],
          0, "Greedy alt problem sonuclarini DP gibi saklamak zorunda degildir."),
        q(56, "Which of the following is NOT a step involved in designing a Greedy algorithm?",
          ["Identifying the subproblems", "Defining the objective function", "Making a greedy choice", "Proving the correctness of the algorithm"],
          0, "Alt problem belirleme DP tasarimina daha yakindir."),
        q(57, "What does the 'WATCH' macro in a simulation module do?",
          ["It terminates the simulation after a certain condition is met.", "It observes variable values in the graphical runtime environment.", "It pauses the simulation at a specific event.", "It synchronizes the simulation across multiple modules."],
          1, "WATCH makrosu degiskeni GUI runtime ortaminda izlenebilir yapar."),
        q(58, "If a simulation module is responsible for decrementing a counter upon each message arrival, what happens when the counter reaches zero?",
          ["The simulation pauses.", "The simulation resets the counter.", "The simulation generates an error.", "The simulation runs out of events and terminates."],
          3, "Yeni olay uretilmezse simülasyon olay kalmadigi icin sonlanir."),
        q(59, "When you have a counter variable in a simulation, and you want to keep track of its value during the simulation run, you would:",
          ["Modify the initialize() function to display the counter.", "Utilize the WATCH macro to observe its value.", "Use a breakpoint to stop the simulation when the counter changes.", "Print the counter value to the console at each decrement."],
          1, "Degeri takip etmek icin WATCH makrosu kullanilir."),
        q(60, "what is the start node and type of graph problem?",
          ["start node 4 and graph type is MCST.", "start node 4 and graph type is DFS.", "start node 0 and graph type is BFS.", "start node 1 and graph type is MCST."],
          0, "PDF'teki agirlikli graph sorusunda beklenen secenek start node 4 ve MCST olarak verilir."),
    ],
})


if __name__ == "__main__":
    print("EXAMS loaded:", [(e["year"], len(e["questions"])) for e in EXAMS])
